import os
import sqlite3
import unittest
from argparse import Namespace
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from db import PostgresCompatConnection, normalize_database_url
from scripts import db_migration
from scripts.db_migration import (
    sqlite_rows_for_migration,
    sqlite_schema_rows,
    sqlite_table_names,
    visual_reference_child_counts,
)


TEST_TMP_DIR = Path(__file__).resolve().parent.parent / "tmp"


class DatabasePortabilityTests(unittest.TestCase):
    def test_railway_postgres_url_is_normalized_with_ssl(self):
        normalized = normalize_database_url("postgres://user:pass@example.railway.internal:5432/railway")

        self.assertTrue(normalized.startswith("postgresql://"))
        self.assertIn("sslmode=require", normalized)

    def test_existing_sslmode_is_preserved(self):
        normalized = normalize_database_url("postgresql://user:pass@example/railway?sslmode=verify-full")

        self.assertIn("sslmode=verify-full", normalized)

    def test_sqlite_insert_or_ignore_translates_to_postgres_conflict_noop(self):
        conn = object.__new__(PostgresCompatConnection)
        sql, params = conn._translate_sql("INSERT OR IGNORE INTO service_history_records (id) VALUES (?)", (7,))

        self.assertIn("INSERT INTO service_history_records", sql)
        self.assertIn("ON CONFLICT DO NOTHING", sql)
        self.assertEqual(params, (7,))

    def test_upsert_self_reference_is_qualified_for_postgres(self):
        conn = object.__new__(PostgresCompatConnection)
        sql, params = conn._translate_sql(
            """
            INSERT INTO metrics(name, value, updated_at)
            VALUES(?, ?, ?)
            ON CONFLICT(name) DO UPDATE SET
                value = value + ?,
                updated_at = ?
            """,
            ("page_home", 1, "now", 1, "now"),
        )

        self.assertIn("value = metrics.value + %s", sql)
        self.assertEqual(params, ("page_home", 1, "now", 1, "now"))

    def test_sqlite_master_sql_lookup_is_synthesized_from_postgres_columns(self):
        class FakeCursor:
            def __init__(self):
                self.params = None
                self.calls = 0

            def execute(self, _sql, params):
                self.params = params
                self.calls += 1

            def fetchall(self):
                if self.calls == 2:
                    return [("CHECK ((customer_decision = ANY (ARRAY['pending'::text, 'deferred'::text])))",)]
                return [("id",), ("customer_decision",), ("deferred_until",)]

        class FakeConn:
            def cursor(self):
                return FakeCursor()

        conn = object.__new__(PostgresCompatConnection)
        conn._conn = FakeConn()

        rows = conn._sqlite_master_table_sql(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'discrepancy_approvals'",
            (),
        )

        self.assertIn("customer_decision", rows[0]["sql"])
        self.assertIn("deferred", rows[0]["sql"])

    def test_group_concat_translates_to_postgres_string_agg(self):
        conn = object.__new__(PostgresCompatConnection)
        sql, _ = conn._translate_sql(
            "SELECT GROUP_CONCAT(invoice_items.repair_record_id) AS repair_record_ids FROM invoice_items",
            (),
        )

        self.assertIn("STRING_AGG((invoice_items.repair_record_id)::text, ',')", sql)

    def test_named_sqlite_params_normalize_to_positional_params(self):
        conn = object.__new__(PostgresCompatConnection)
        sql, params = conn._normalize_params(
            "VALUES (:year, :make, :year)",
            {"year": 2001, "make": "Mercedes-Benz"},
        )

        self.assertEqual(sql, "VALUES (?, ?, ?)")
        self.assertEqual(params, (2001, "Mercedes-Benz", 2001))

    def test_sqlite_autoincrement_translates_to_postgres_identity(self):
        conn = object.__new__(PostgresCompatConnection)
        os.environ["TORQUEMECH_ALLOW_RUNTIME_SCHEMA"] = "1"
        try:
            sql, _ = conn._translate_sql(
                "CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)",
                (),
            )
        finally:
            os.environ.pop("TORQUEMECH_ALLOW_RUNTIME_SCHEMA", None)

        self.assertIn("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
        self.assertNotIn("AUTOINCREMENT", sql)

    def test_schema_migration_orders_parent_tables_before_foreign_key_children(self):
        conn = sqlite3.connect(":memory:")
        conn.row_factory = sqlite3.Row
        try:
            conn.executescript(
                """
                CREATE TABLE child (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    parent_id INTEGER NOT NULL,
                    FOREIGN KEY (parent_id) REFERENCES parent(id)
                );
                CREATE TABLE parent (
                    id INTEGER PRIMARY KEY AUTOINCREMENT
                );
                CREATE INDEX idx_child_parent_id ON child(parent_id);
                """
            )

            ordered_names = [row["name"] for row in sqlite_schema_rows(conn)]
        finally:
            conn.close()

        self.assertLess(ordered_names.index("parent"), ordered_names.index("child"))
        self.assertLess(ordered_names.index("child"), ordered_names.index("idx_child_parent_id"))

    def test_data_migration_orders_parent_tables_before_foreign_key_children(self):
        conn = sqlite3.connect(":memory:")
        conn.row_factory = sqlite3.Row
        try:
            conn.executescript(
                """
                CREATE TABLE child (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    parent_id INTEGER NOT NULL,
                    FOREIGN KEY (parent_id) REFERENCES parent(id)
                );
                CREATE TABLE parent (
                    id INTEGER PRIMARY KEY AUTOINCREMENT
                );
                """
            )

            ordered_names = sqlite_table_names(conn)
        finally:
            conn.close()

        self.assertEqual(ordered_names, ["parent", "child"])

    def test_visual_reference_child_filter_reports_and_keeps_valid_rows_only(self):
        conn = sqlite3.connect(":memory:")
        conn.row_factory = sqlite3.Row
        original_expected = db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"]
        db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"] = (3, 2, 1)
        try:
            conn.executescript(
                """
                CREATE TABLE visual_reference_records (id INTEGER PRIMARY KEY);
                CREATE TABLE visual_reference_hotspots (
                    id INTEGER PRIMARY KEY,
                    visual_reference_id INTEGER NOT NULL,
                    label TEXT
                );
                INSERT INTO visual_reference_records (id) VALUES (1), (2);
                INSERT INTO visual_reference_hotspots (id, visual_reference_id, label)
                VALUES (10, 1, 'valid-a'), (11, 2, 'valid-b'), (12, 99, 'orphan');
                """
            )

            self.assertEqual(visual_reference_child_counts(conn, "visual_reference_hotspots"), (3, 2, 1))
            rows = sqlite_rows_for_migration(conn, "visual_reference_hotspots")
        finally:
            db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"] = original_expected
            conn.close()

        self.assertEqual([row["id"] for row in rows], [10, 11])

    def test_visual_reference_child_filter_aborts_on_unexpected_counts(self):
        conn = sqlite3.connect(":memory:")
        conn.row_factory = sqlite3.Row
        original_expected = db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"]
        db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"] = (99, 98, 1)
        try:
            conn.executescript(
                """
                CREATE TABLE visual_reference_records (id INTEGER PRIMARY KEY);
                CREATE TABLE visual_reference_hotspots (
                    id INTEGER PRIMARY KEY,
                    visual_reference_id INTEGER NOT NULL,
                    label TEXT
                );
                INSERT INTO visual_reference_records (id) VALUES (1);
                INSERT INTO visual_reference_hotspots (id, visual_reference_id, label)
                VALUES (10, 1, 'valid'), (11, 2, 'orphan');
                """
            )

            with self.assertRaises(SystemExit):
                sqlite_rows_for_migration(conn, "visual_reference_hotspots")
        finally:
            db_migration.VISUAL_REFERENCE_CHILD_TABLES["visual_reference_hotspots"] = original_expected
            conn.close()

    def test_local_subscriptions_schema_command_creates_only_expected_objects(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_local_subscriptions_schema_create.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        with patch.dict(os.environ, {}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            output = StringIO()
            with redirect_stdout(output):
                db_migration.apply_subscriptions_schema_local(Namespace())

        conn = sqlite3.connect(sqlite_path)
        try:
            rows = conn.execute(
                """
                SELECT type, name
                FROM sqlite_master
                WHERE name NOT LIKE 'sqlite_%'
                ORDER BY type, name
                """
            ).fetchall()
        finally:
            conn.close()

        self.assertIn(str(sqlite_path.resolve()), output.getvalue())
        self.assertEqual(
            rows,
            [
                ("index", "idx_shop_subscriptions_shop_id"),
                ("index", "idx_shop_subscriptions_status"),
                ("table", "shop_subscriptions"),
            ],
        )

    def test_local_subscriptions_schema_command_is_idempotent(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_local_subscriptions_schema_idempotent.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        with patch.dict(os.environ, {}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            db_migration.apply_subscriptions_schema_local(Namespace())
            db_migration.apply_subscriptions_schema_local(Namespace())

        conn = sqlite3.connect(sqlite_path)
        try:
            count = conn.execute(
                """
                SELECT COUNT(*)
                FROM sqlite_master
                WHERE name IN (
                  'shop_subscriptions',
                  'idx_shop_subscriptions_shop_id',
                  'idx_shop_subscriptions_status'
                )
                """
            ).fetchone()[0]
        finally:
            conn.close()

        self.assertEqual(count, 3)

    def test_local_subscriptions_schema_command_refuses_when_database_url_is_set(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_local_subscriptions_schema_refusal.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        with patch.dict(os.environ, {"DATABASE_URL": "sqlite:///local.db"}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            with self.assertRaises(SystemExit) as raised:
                db_migration.apply_subscriptions_schema_local(Namespace())

        self.assertIn("DATABASE_URL is set", str(raised.exception))
        self.assertFalse(sqlite_path.exists())

    def test_sqlite_cancel_at_period_end_migration_adds_column_and_preserves_rows(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_cancel_at_period_end_migration.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        conn = sqlite3.connect(sqlite_path)
        try:
            conn.executescript(
                """
                CREATE TABLE shop_subscriptions (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  shop_id INTEGER NOT NULL UNIQUE,
                  plan_code TEXT NOT NULL DEFAULT 'pro_solo',
                  status TEXT NOT NULL,
                  trial_started_at TEXT,
                  trial_ends_at TEXT,
                  current_period_started_at TEXT,
                  current_period_ends_at TEXT,
                  canceled_at TEXT,
                  access_grace_ends_at TEXT,
                  stripe_customer_id TEXT,
                  stripe_subscription_id TEXT,
                  stripe_price_id TEXT,
                  created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL
                );
                INSERT INTO shop_subscriptions (shop_id, plan_code, status, created_at, updated_at)
                VALUES (7, 'pro_solo', 'active', '2026-07-22T12:00:00+00:00', '2026-07-22T12:00:00+00:00');
                """
            )
            conn.commit()
        finally:
            conn.close()

        with patch.dict(os.environ, {}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            db_migration.add_subscription_cancel_at_period_end_sqlite(Namespace())

        conn = sqlite3.connect(sqlite_path)
        conn.row_factory = sqlite3.Row
        try:
            columns = {row["name"]: row for row in conn.execute("PRAGMA table_info(shop_subscriptions)").fetchall()}
            row = conn.execute("SELECT * FROM shop_subscriptions WHERE shop_id = 7").fetchone()
        finally:
            conn.close()

        self.assertIn("cancel_at_period_end", columns)
        self.assertEqual(columns["cancel_at_period_end"]["type"].upper(), "INTEGER")
        self.assertEqual(columns["cancel_at_period_end"]["notnull"], 1)
        self.assertEqual(str(columns["cancel_at_period_end"]["dflt_value"]), "0")
        self.assertEqual(row["status"], "active")
        self.assertEqual(row["cancel_at_period_end"], 0)

    def test_sqlite_cancel_at_period_end_migration_is_idempotent(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_cancel_at_period_end_migration_idempotent.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        conn = sqlite3.connect(sqlite_path)
        try:
            conn.execute(
                """
                CREATE TABLE shop_subscriptions (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  shop_id INTEGER NOT NULL UNIQUE,
                  status TEXT NOT NULL,
                  created_at TEXT NOT NULL,
                  updated_at TEXT NOT NULL
                )
                """
            )
            conn.commit()
        finally:
            conn.close()

        with patch.dict(os.environ, {}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            db_migration.add_subscription_cancel_at_period_end_sqlite(Namespace())
            db_migration.add_subscription_cancel_at_period_end_sqlite(Namespace())

        conn = sqlite3.connect(sqlite_path)
        try:
            count = sum(
                1
                for row in conn.execute("PRAGMA table_info(shop_subscriptions)").fetchall()
                if row[1] == "cancel_at_period_end"
            )
        finally:
            conn.close()

        self.assertEqual(count, 1)

    def test_sqlite_cancel_at_period_end_migration_refuses_when_database_url_is_set(self):
        TEST_TMP_DIR.mkdir(parents=True, exist_ok=True)
        sqlite_path = TEST_TMP_DIR / "test_cancel_at_period_end_migration_refusal.db"
        sqlite_path.unlink(missing_ok=True)
        self.addCleanup(lambda: sqlite_path.unlink(missing_ok=True))
        with patch.dict(os.environ, {"DATABASE_URL": "sqlite:///local.db"}, clear=True), patch.object(
            db_migration.db,
            "active_app_db_path",
            return_value=str(sqlite_path),
        ):
            with self.assertRaises(SystemExit) as raised:
                db_migration.add_subscription_cancel_at_period_end_sqlite(Namespace())

        self.assertIn("DATABASE_URL is set", str(raised.exception))
        self.assertFalse(sqlite_path.exists())

    def test_postgres_cancel_at_period_end_migration_uses_boolean_default_false(self):
        statements = []

        class FakeCursor:
            def __enter__(self):
                return self

            def __exit__(self, *_exc):
                return False

            def execute(self, sql):
                statements.append(str(sql))

            def fetchone(self):
                return None

        class FakePgConn:
            def __enter__(self):
                return self

            def __exit__(self, *_exc):
                return False

            def cursor(self):
                return FakeCursor()

            def rollback(self):
                statements.append("ROLLBACK")

            def close(self):
                statements.append("CLOSE")

        with patch.dict(os.environ, {"DATABASE_URL": "postgresql://user:pass@example/db"}, clear=True), patch.object(
            db_migration,
            "pg_connect",
            return_value=FakePgConn(),
        ):
            db_migration.add_subscription_cancel_at_period_end_postgres(Namespace())

        combined = "\n".join(statements)
        self.assertIn("ALTER TABLE shop_subscriptions", combined)
        self.assertIn("ADD COLUMN cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE", combined)

    def test_postgres_cancel_at_period_end_migration_requires_postgres_database_url(self):
        with patch.dict(os.environ, {}, clear=True):
            with self.assertRaises(SystemExit) as raised:
                db_migration.add_subscription_cancel_at_period_end_postgres(Namespace())

        self.assertIn("explicit PostgreSQL URL", str(raised.exception))


if __name__ == "__main__":
    unittest.main()
