from __future__ import annotations

import argparse
import os
import shutil
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from db import DB_PATH, normalize_database_url


ACCOUNT_COLUMNS = {
    "trial_started_at": "TEXT",
    "trial_ends_at": "TEXT",
    "subscription_status": "TEXT",
    "stripe_customer_id": "TEXT",
    "stripe_subscription_id": "TEXT",
    "subscription_current_period_end": "TEXT",
    "subscription_cancel_at_period_end": "INTEGER",
}

VISUAL_REFERENCE_CHILD_TABLES = {
    "visual_reference_images": (200, 5, 195),
    "visual_reference_specs": (280, 7, 273),
    "visual_reference_oem_parts": (240, 6, 234),
    "visual_reference_hotspots": (160, 4, 156),
}


def sqlite_connect(sqlite_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(str(sqlite_path))
    conn.row_factory = sqlite3.Row
    return conn


def pg_connect():
    import psycopg2

    dsn = normalize_database_url()
    if not dsn:
        raise SystemExit("DATABASE_URL is required for PostgreSQL migration commands.")
    return psycopg2.connect(dsn)


def psycopg_sql():
    from psycopg2 import sql

    return sql


def psycopg_execute_values():
    from psycopg2.extras import execute_values

    return execute_values


def translate_schema_sql(raw_sql: str) -> str:
    translated = raw_sql.replace("AUTOINCREMENT", "")
    translated = translated.replace(
        "INTEGER PRIMARY KEY",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    translated = translated.replace(
        '"discrepancy_approvals_old"',
        '"discrepancy_approvals"',
    )
    translated = translated.replace(
        "IF NOT EXISTS IF NOT EXISTS",
        "IF NOT EXISTS",
    )
    return translated


def quote_sqlite_identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def sqlite_schema_rows(sqlite_conn: sqlite3.Connection) -> list[sqlite3.Row]:
    rows = sqlite_conn.execute(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_master
        WHERE sql IS NOT NULL
          AND name NOT LIKE 'sqlite_%'
        ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name
        """
    ).fetchall()
    table_rows = [row for row in rows if row["type"] == "table"]
    other_rows = [row for row in rows if row["type"] != "table"]
    return ordered_table_rows(sqlite_conn, table_rows) + other_rows


def ordered_table_rows(sqlite_conn: sqlite3.Connection, rows: list[sqlite3.Row]) -> list[sqlite3.Row]:
    by_name = {row["name"]: row for row in rows}
    remaining = set(by_name)
    emitted: list[str] = []

    dependencies: dict[str, set[str]] = {}
    for table_name in by_name:
        deps = set()
        for fk in sqlite_conn.execute(f"PRAGMA foreign_key_list({quote_sqlite_identifier(table_name)})").fetchall():
            referenced_table = fk["table"] if isinstance(fk, sqlite3.Row) else fk[2]
            if referenced_table in by_name and referenced_table != table_name:
                deps.add(referenced_table)
        dependencies[table_name] = deps

    while remaining:
        ready = sorted(
            table_name
            for table_name in remaining
            if not (dependencies[table_name] & remaining)
        )
        if not ready:
            # Cycles are not expected in the current app schema. Keep output deterministic
            # so a failed migration is repeatable and easy to inspect.
            ready = sorted(remaining)
        for table_name in ready:
            emitted.append(table_name)
            remaining.remove(table_name)

    return [by_name[table_name] for table_name in emitted]


def sqlite_table_names(sqlite_conn: sqlite3.Connection) -> list[str]:
    rows = sqlite_conn.execute(
        """
        SELECT name, type, tbl_name, sql
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [row["name"] for row in ordered_table_rows(sqlite_conn, rows)]


def visual_reference_child_counts(sqlite_conn: sqlite3.Connection, table_name: str) -> tuple[int, int, int]:
    if table_name not in VISUAL_REFERENCE_CHILD_TABLES:
        raise ValueError(f"Unexpected visual reference child table: {table_name}")
    quoted_table = quote_sqlite_identifier(table_name)
    source_total = sqlite_conn.execute(f"SELECT COUNT(*) FROM {quoted_table}").fetchone()[0]
    valid_count = sqlite_conn.execute(
        f"""
        SELECT COUNT(*)
        FROM {quoted_table}
        WHERE visual_reference_id IN (
            SELECT id FROM visual_reference_records
        )
        """
    ).fetchone()[0]
    excluded_count = source_total - valid_count
    return source_total, valid_count, excluded_count


def validate_visual_reference_child_counts(sqlite_conn: sqlite3.Connection, table_name: str) -> None:
    observed = visual_reference_child_counts(sqlite_conn, table_name)
    expected = VISUAL_REFERENCE_CHILD_TABLES[table_name]
    print(
        f"{table_name}: source_total={observed[0]} valid_rows={observed[1]} "
        f"excluded_orphans={observed[2]}"
    )
    if observed != expected:
        raise SystemExit(
            f"Unexpected {table_name} visual-reference filter counts: "
            f"observed total={observed[0]}, valid={observed[1]}, excluded={observed[2]}; "
            f"expected total={expected[0]}, valid={expected[1]}, excluded={expected[2]}. "
            "Stop and inspect before migrating."
        )


def sqlite_rows_for_migration(sqlite_conn: sqlite3.Connection, table_name: str) -> list[sqlite3.Row]:
    quoted_table = quote_sqlite_identifier(table_name)
    if table_name in VISUAL_REFERENCE_CHILD_TABLES:
        validate_visual_reference_child_counts(sqlite_conn, table_name)
        return sqlite_conn.execute(
            f"""
            SELECT *
            FROM {quoted_table}
            WHERE visual_reference_id IN (
                SELECT id FROM visual_reference_records
            )
            """
        ).fetchall()
    return sqlite_conn.execute(f"SELECT * FROM {quoted_table}").fetchall()


def backup_sqlite(args: argparse.Namespace) -> None:
    source = args.sqlite_path.resolve()
    if not source.exists():
        raise SystemExit(f"SQLite database not found: {source}")
    backup_dir = args.backup_dir.resolve()
    backup_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    destination = backup_dir / f"{source.stem}.{stamp}.bak{source.suffix}"
    shutil.copy2(source, destination)
    print(destination)


def migrate_schema(args: argparse.Namespace) -> None:
    sqlite_path = args.sqlite_path.resolve()
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    sqlite_conn = sqlite_connect(sqlite_path)
    pg_conn = pg_connect()
    try:
        pg_sql = psycopg_sql()
        sqlite_rows = sqlite_schema_rows(sqlite_conn)
        with pg_conn:
            with pg_conn.cursor() as cur:
                for row in sqlite_rows:
                    cur.execute(translate_schema_sql(row["sql"]))
                for column_name, column_type in ACCOUNT_COLUMNS.items():
                    cur.execute(
                        pg_sql.SQL("ALTER TABLE users ADD COLUMN IF NOT EXISTS {} {}").format(
                            pg_sql.Identifier(column_name),
                            pg_sql.SQL(column_type),
                        )
                    )
        print(f"Schema migrated from {sqlite_path}")
    finally:
        sqlite_conn.close()
        pg_conn.close()


def migrate_data(args: argparse.Namespace) -> None:
    sqlite_path = args.sqlite_path.resolve()
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite database not found: {sqlite_path}")

    sqlite_conn = sqlite_connect(sqlite_path)
    pg_conn = pg_connect()
    try:
        pg_sql = psycopg_sql()
        execute_values = psycopg_execute_values()
        tables = sqlite_table_names(sqlite_conn)
        with pg_conn:
            with pg_conn.cursor() as cur:
                for table_name in tables:
                    rows = sqlite_rows_for_migration(sqlite_conn, table_name)
                    if not rows:
                        continue
                    columns = rows[0].keys()
                    cur.execute(pg_sql.SQL("SELECT COUNT(*) FROM {}").format(pg_sql.Identifier(table_name)))
                    existing_count = cur.fetchone()[0]
                    if existing_count and not args.append:
                        raise SystemExit(
                            f"PostgreSQL table {table_name} already has {existing_count} rows. "
                            "Use --append only after confirming duplicates are impossible."
                        )
                    values = [tuple(row[column] for column in columns) for row in rows]
                    insert_sql = pg_sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
                        pg_sql.Identifier(table_name),
                        pg_sql.SQL(", ").join(pg_sql.Identifier(column) for column in columns),
                    )
                    execute_values(cur, insert_sql, values)
                    if "id" in columns:
                        cur.execute(
                            """
                            SELECT setval(pg_get_serial_sequence(%s, 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL)
                            FROM {table}
                            """.format(table=pg_sql.Identifier(table_name).as_string(cur)),
                            (table_name,),
                        )
                    print(f"{table_name}: {len(rows)} rows")
        print(f"Data migrated from {sqlite_path}")
    finally:
        sqlite_conn.close()
        pg_conn.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="TorqueMech SQLite to PostgreSQL migration helper")
    parser.add_argument("--sqlite-path", type=Path, default=Path(DB_PATH))
    subparsers = parser.add_subparsers(dest="command", required=True)

    backup = subparsers.add_parser("backup-sqlite")
    backup.add_argument("--backup-dir", type=Path, default=Path("backups"))
    backup.set_defaults(func=backup_sqlite)

    schema = subparsers.add_parser("migrate-schema")
    schema.set_defaults(func=migrate_schema)

    data = subparsers.add_parser("migrate-data")
    data.add_argument("--append", action="store_true")
    data.set_defaults(func=migrate_data)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
